apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: test-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCkDnQpdMPxIH2tbSD/F6O7+GZ+PgyPsGY0UW8jXKMT4PkljK3onlf2xkwiLQPvk9jxqC3RZqIbnr7KP41essaB1KTdivg+rpFTklFUaZY1+EZXvgW03XxEm8bqvPz4uEFG7VUUbgGNX4bGtmtLfEqhpOLRq+5snDYX+KNJuEUBe8wGfFqccWVwQumIvfcnrD8Zoc7xaLyvxEPsFsbE3HjBJazpq1CPHqhuJJJZUNNafiYsHX+598XZym2pYINsp6dG2RoUy6Toju0SrKBXtQABztDba3TzRzUIn9i/nCrbRFwfNfEwIA0l2y/8IB7aTovBvrz1taBH9T8OqGaMq06svh3UsG4Qrf4uf2xGnZHTrFFq4chp8P1VnpNo753MbuKvU5qKXzCJ/odBA/eydbC5l31i+b70JlPSmr5qbXGI9Sn4gZxkhvYbVAjTR99vCTHU5tnDSL2BvN5OcrvpHD5eRTF2iASKyDxweyko+Ad0/9Q/L/tXbsNfIWWdu1SbkKUt8fu1DXtiG/buqrXPSyIAV0pu8jaWZsqj+IfG2IVNwRvNyst4nb+abjV0LX6qadxVVVg5X3rqvkWTqXG3xNpnbfiD3AU1qpGBk4sc4nsY8INkwjD+MLO8Fz5CijCv004w0I8DRUusEiaSXD+IBDuW6hih3TdU01uqKYNtrBLQdnMR46vVFD5HaSWnVdelBp0Jf7iHZ6g=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: test-cicd
    type: Opaque
status: {}
