apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: test-cicd
spec:
  encryptedData:
    webhook-secret-key: AgApJq5rby0cy2jkRPnW7bR8tprkTI6rvc/lyydJf60axBPmJGHKLh4FBUcmeLx+SxB49q+eInMWdGkwSYgCgzz/QR5UGvvJLCRkHO94mXW4/klKCyttw+qJNwpgbxovAmIN8iLtpL32kEsSOYINc3OAguegXzZ1B8oWzqpynKLKwtNXXH3UPS9ywe+0wE/SetPW+CG3E19vF/uYxcQjrTD3CgmZ95EaO2ecTliHmPraqrIrV8hRG0WXT24TCcXE97qAswYLSmmeU5iJXydrgikFkGxPtG3T+B4VlP8Dvp1DKjzS9LjkbOxgIHgWYXRh0lljc+bs3E5jKOl0Z/fNjFBgSnDtbUPbhOFHnKZfxWYNkcs5+yIelac9zLj3KCCjzB+3UyxXQ3nU+QDO+I7wZ5kck1XPQ9t3sshf8CEktjdzIfn/4VgMDTdpQfKkyO4J0DvBxuArGneZq/IS2bDfeZFPQIBD4SzTSjt4gVcvW2pTuATPvmnlb7w5ihQR95Yxug7KNOosdhdG4FBuGoJppt6S2VMRFXtVE3JoD++0g7HA9s/RKCAokMwHPSSDQ7lpOSJ44q3amcLkSOedTpEDcBBQRN+k9NxNvTvoELd1lguX89T9sLpR8CL/YLVHynXkDm10m28vcQfzFfOLttdAVIL8X19AsVT3se9thlYKSs01LLq6x/TfL8A1kd0gMq/l8R06GAgUCWN19PIlBpTXg8afzurjbw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: test-cicd
    type: Opaque
status: {}
