apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-test-dev-taxi
  namespace: test-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAf9w+02l60LJPElWHBAHnu92NFYezgyiAJ911sQILFxIoKCHYoTJK3MWkWmG2SYIHDmDnBbkInEhIZ5xHPJsto9kaLNUwWVZtSQKDunCdNwpuNsUvQimaC4kHYo2W+eT8vydBYRllKHjyUuUCR2ZYh89/pkwdfFbCBJpKGv4fS0dUcPNUBZnkPpEr9Kaod1LtoOuVM+o5UR/GoV6r3BBKnnsLwYJwWuru3hV/pgkLeq3Kc8G3Dl3/0FkmeBYRuA1C1vFxuRXGiDNgvg2sEtQuJZvkrY8iLLH/SRFyzluQEd+RXqjEy6fSqVheu09N+kIpCdUALyoa0tqFXTInuoOKGx+Mm494/grAvM8gJ/o8/I3ZMSY+peZCtsAWeF0J1+0JsUPN0RN7MKfTcaFtBPogv50Yx6PyOA52puGfuubaBnM2wVH/+XR9LHrpWoAjeFoijY0PwgpIr5ofO+tKEZkG4Csdu1Rj70wvPk7cBQrWYjyW2A631v0+MNnQBaJhBaZegFFMgmrSnp46/55iBQMgbYuaFX3PucydAc54I1H7VkIcQek9IBQNASArhrn7eKJrEpyPDrP3r+FG8iD+ocssc8G93NWuQmFVMTZstg2cwSniRUzVFMb3sIR5a1JLi40gyugBbCuWgy5pkkVgoL/h+jQp+FYd7sz3YqnbVXkbTB7KwX68bSeZznXotO1xRxkox46kHenk=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-test-dev-taxi
      namespace: test-cicd
    type: Opaque
status: {}
