apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ishita-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCqyj/WCtb7L53hrK+59PMmEv0WwuLHLA1Ck67TVJgngtdwO/7leDlCtEt+kOUF+CZcRDo6YhoDEgP6LGPfxCeDzfwjzcOAIYRFOT0lArXeBYER7Q6jO9qyayrwZBNZoPcrJK9rBP0IxUX55D3J0NZCRs2MjdF5sr1rQ41tLrGXlp0jYZdqXLdp8DrA0z4hrL7+6tO6bRqINdGVXERF2ugnzCexYV+816vh8+IaiK7D8qrjddKKkgxCURN88O9rswML/kc20v01ksTpNwcIjKYGxyNavi5jivhOFLegzp8nVryh0b+H5KHjtfWtMGM7GR5xYWfNgbnd3tLSQDsfkTkB22IxfJg38D0fIGymYYevcjGrsyi6NG6qdJE10FE1kPl4pL4QZE8ccOJWUo28eqM5zy4Y1UGmrKlrscB31FhcHKuInZICcu7ktt9bhXCHIbaBoUkBIjpSVvH+X73xPUyy6a7WLI8rf8AgBY8Xgfl7tFSLN/KrEAp5QwlFKOgAMLqGbLtCmsJy7AJ2dVacfrhhftLfUaruo3uXK9Sk8fHo/HiJxxVKSE85JLwFp+GBjAR2Dbm493HiTEeXv58o/Bu7fxg03/qseBZlLEafwhX1pRiMpTCmy0jqP4BMOR8ljVOPSJ/fipBEibDl/2UBEItAy4bb4AkNIivgOS5GHqNKT4+dlEjXXMQJo9u+A4weHvFcYbUeFlJQlaXdV6cyDdl9xm5qQ2RpgdEBDNV/FDLoz3gcxd9CUKPx0Z3XitZWoH5lEfJzDToLDGY4WT/IeUiri0TUnyyc8yFdSo9bn/bdXe3Q3c8N9L/zqC6/7csNRhFom05VicJXX6fHHp0WNeb2aVxN78cTGvR9SRrQodiAhTSDfkzheLWQ4j6KTR2rIiL18FcANaUNRhzTQ+4FlKL1doPbbxsOUgC4lQ2ea7PlcVrQEE1dM139bhTa
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ishita-cicd
    type: kubernetes.io/dockerconfigjson
status: {}
