apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: ishita-cicd
spec:
  encryptedData:
    webhook-secret-key: AgB3HJuH3Eqb3x1TTJfx8tFSrrbxQuMCQKbGTPg8WZVybUIDptuyD9G3I7Ns1qqzP6fpz2WHiOLMVABCM6M3HHKs03u3L/f5kZf9SaE0MIPkc32AvVhJgDe0XRfH9UmOpukhx1GLXKzusMuNuKQyVSFT0EgB6q+XX/wYqffY8FuVL6hvNZVF8ec3AP88602V7287lM1X+uFXof7zlH0y/3yYaTo0ySJGXeARDrPjsplFSYP3AoPgfVO8exE3bY5d3uf2zV1f6CvQvROhgmZTxLFatvvo6Qvrz6mFduW2mXyb/JNcm9JbdrDzkI6Tpxk73U4hleQQcGlrEsg6hX90j8uS/g46RusuCu8yx3HadKE8kQSk+/FqVEWVVRezgym1ScuT9T3h68q0bnDk4xlZKRcS0/9C5kVxHb038Ha4tgiJ9TVoGIkczTjwMat8oiyXfwBalV6gJY5u5+X5rtnPHm9PhM1fawCPoCXhdf2eGOw0Zx+t01+PBWDxe2KwC/rd6tCpaepyua0sWkkdq6Cj2JW3uTGNf6yZU3ZVMIS5uUbZFFodPEgzcLtDyqnMNYXK7+RQN2N7vpminL9xhkVY/e7zfRTbtml5YcTJAXUKH9vtkKsNNu5+8YAJFIkocHamex3zXkQWz6Z+YFrLz7+Kh8/1MTP5+12xbBcjuwM/TlFepHiUWdv6T1pCAIH5JDTBrsEmB6YxPNEQAfk0kT3MAa2w0H0+nQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: ishita-cicd
    type: Opaque
status: {}
