apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBl/pDojR+j4E5JylPTNbIMFCjop/xJD4rUiSlN4B4CqDHagdWh1LxSbv5i31ojspEnL/af4K1csYXZE+79Mirt5um9EAVzaDan7XFe0ZuWeQ3+qGT0ww3Ag0BfMbLDAdGXJBbTYNpNJUfyA/YIltRkaoADDpJkv+jhdGumwVULdRWBcWPRt/oR7sGgERUVpYFryFny1yCHlbZs/FzKrnh4tjk0AOeHkFcC0SDBZwZBNodwjZNn2ifboF+B3Pi4cxeJ8Ay2IvZCAviT17rKVtqFM+R+QGiBDYfIPT5l6WyWZq0U58KW6fnBRzB8U3T9Cn/C49HbVGLe/4qjQzNVbaqx713lmwHIm3iV+3Q8jkfqU+Uhy8z6Rt5+FLgTTXtkyDvSBh5S3712dkVCbv1s1Am4WsyXJQp+sWbtHF8q6xiIwZQj6F/fV1DENIJEWi1BPK1RBnbDgXn8M1EogG0x/9Zx3VuWGgq3ruQidr3DmAnLMK4M9OclQsidXOZl+MQf4hQK9KA77sXO1DN40uiznRcySx/Rv69nANDB+9QsQ2Rp46wGzX0c/nKGS57fl34issOB2TueNA8/1FLrpd9XWx65kvwmDSK7Y7N+ZxJKeerDT2pQx49RPO9DGTWOI9e9pAbfWw36DxCQU3UpMRaTDgSIFlruwvh6eNgb5wUJgN5He8WiBaSzfP+DoqQmIoUyh+sH/l3NCtxYzinSEZriTCHaWS4ytw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: demo-cicd
    type: Opaque
status: {}
