apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: cd-deploy-from-push-template
  namespace: demo-cicd
spec:
  params:
  - default: master
    description: The git revision
    name: io.openshift.build.commit.ref
  - description: The git repository url
    name: gitrepositoryurl
  - description: The date at which the commit was made
    name: io.openshift.build.commit.date
  - description: The name of the github user handle that made the commit
    name: io.openshift.build.commit.author
  - description: The commit message
    name: io.openshift.build.commit.message
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: cd-deploy-from-push-pipeline-$(uid)
    spec:
      pipelineRef:
        name: cd-deploy-from-push-pipeline
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(params.io.openshift.build.commit.ref)
          - name: url
            value: $(params.gitrepositoryurl)
          type: git
      serviceAccountName: pipeline
    status: {}
status: {}
