apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAYYBESkGbGb95U1v8V3Rk//m/PJo1JGhiuW/gEPDftOYBFUcKaxp7DKRHsfFY3mGDJ+tj6Dsmc7EHCk1xuqWM9D4lSW05aSegSHR5YYu/u/SB1yLNkpj36Rb2v9NvNeBcFmOPOOKvikGksbt89XHSlluLCbb8TA6pRhqyZO8n97Z3b5vV3hqyqRj/G+qhjurW7bPduGja70t7BlMAH2npamY4fDLu5A9Vg2mmQNWGPc6vq67QsXPA78Motq1HFfNUiENvne5dx3x3oeLNfha5LnQ6Zj4EBHlFMLpHdre1lJwBJCBJ5Y+/HuGfjwXQ6cLz7x5FiGIzXHlnv8rno6M3zFad3K69+gP/5b40whIflktTPPNwGQcFuajsV2rIuLD1RkDcWcUwLoRA3xmXB4T7y3Ucvmn+5CtkQTV/sHzQU8ME2ZJ2gx63HADPTZRHylEpsQCL48O9s30RtrOAj4gE2ztNak3UikBLoP/P05JGGLTvClCHq/VkXYleO7uLZO8SXz4L5sIzMtDgppPOy59Vy0EQuSoMWkKV/O7SXwGQs87k/wl1Xj6DR4Fz65uM1DxjlQkKm3CePP8FFRdxE3c/RX3ExkKXiakGUSr8JFj3JS9S1p9Qb9wN/RgyeRfveF7W6o6Dqlel5yqS10L3FzHJDWSsFXI9Ec5UvgGZHIEbVLS3XgMNJQRQE4O9N2T9UZAmfBkmESuEdUnFfv7o/MwUqrg7inw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
