resources:
- 01-namespaces/cicd-environment.yaml
- 02-rolebindings/commit-status-tracker-role.yaml
- 02-rolebindings/commit-status-tracker-rolebinding.yaml
- 02-rolebindings/commit-status-tracker-service-account.yaml
- 02-rolebindings/pipeline-service-account.yaml
- 02-rolebindings/pipeline-service-role.yaml
- 02-rolebindings/pipeline-service-rolebinding.yaml
- 03-secrets/commit-status-tracker.yaml
- 03-secrets/docker-config.yaml
- 03-secrets/gitops-webhook-secret.yaml
- 03-secrets/webhook-secret-sunday-dev-taxi.yaml
- 04-tasks/deploy-from-source-task.yaml
- 04-tasks/deploy-using-kubectl-task.yaml
- 05-pipelines/app-ci-pipeline.yaml
- 05-pipelines/ci-dryrun-from-push-pipeline.yaml
- 06-bindings/github-push-binding.yaml
- 06-bindings/sunday-dev-taxi-binding.yaml
- 07-templates/app-ci-build-from-push-template.yaml
- 07-templates/ci-dryrun-from-push-template.yaml
- 08-eventlisteners/cicd-event-listener.yaml
- 09-routes/gitops-webhook-event-listener.yaml
- 10-commit-status-tracker/operator.yaml
