apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: test13-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBg/V0CXpzgecm/V/j6Ga/Q8we8yF1TOhca89PlETZrfC8WsXdHSEfGUbXdA2sn8l6i834sTUIgfw0ebE4b+AoKrC2sOyUj2BtxLJYQoDjxpJdO8m1t3IT5BkzfO67Wvkhpw+3x5d077HDFVGEt9xxkKwpY1Rv4JASKb3FOAaTtzfM4/ftGuZ8R5Gnf/FMgQ7OkPlOY8Mk2SYLG4eTHDBfB2gLgCX0BABv9Ph4Ok6p3NUgNcwHGV+dfpiLRqCUZPgh6uHm3pojM0ygXEMPjd8IJkiNNvOJJKl7+GR32XTEMTWWkJSOZsw3lAP/Ip+xBdM/4WnKlHNfzHplwn1yw0C/PcKgVw8GzWcirZKiXovDNU/FmUOQe5Mdrgw7wQcTim7RxTGn9dRasXljlPWPTmo6W40CJkWm5s4ffRHQmRpoVxDU4qAOJ0azy42fBTpD8oj9oJ2zcNjO0bCq6PmiR704OngxJywISjaEFoDYFLhfGW45sJ5rAVPWJaezAo6NNwdc4wJse0lKts/cq5U0hgrew2iwph02UEXrdSbk2ZinLyEWHgo8tOZuVq9ULURQfEH2xO3ySgt3icnDNtwaPrBS/ZYP8N4NxVSdB/LAkvil54lnkmaXTDHUoBT5/fGP/J+Wzd0yx7EIS5fntGTuEZUBqWkGLVdyi5REpp4P1ltvzRYhjtNDm3LNMETGKhx2V6lrvrMCE/F0tWWH3pPLAGyVOb9xz3A==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: test13-cicd
    type: Opaque
status: {}
