apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-test13-dev-taxi
  namespace: test13-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBg3Nm7C2RW9RsqhvROidPOU/6FGf7QFPPaHCenmWJHfhzuKXayqKz0eoJU7uUcm1XeIUFP9WGTHkV/0KI0wUP/2c/96RqPs8zhQOGZoNhubTlRSan3rh0q09clXQnTNmnyCZy7/7nGVXQn6UWft0P9RZPV72snl5xwi7uNxz2iYnegnvAJhszDKFoy0v+pBRXKHYxdHnZdG0KedYzjEZC+bjbyZfC8vPVDVSnqetmo48zJUHtu3KgrGrK4sTBxZhXgfpzpxqNiRA2P9zas8a8EisBib3fPJ2nx1VtB7m/NUx4/RgbshTpT3/9EHSjT5tMhc4Qu6C1YwyELSszhRoKvu1cZNXSMok3sTIk4wE+TP+tfs+jqav3pLbfFRMQvnyUoOIY+jxOG4js5L1FWqwy09nGaGktEPzSTwVl+RfOfyDb+TeDpjh92FcKaQwyzU41tfZGTQ2jn1g89uxOXKEbD53Kf129k7NZMSOcNW1VxQ5olP8WMoVSi3u8wZgMdq4HHW11Q/Lzujd+4bh4tJsdiNDUwQJGPMneXsVzxPnqac/bTbUwLlc3i/irMEqttIQy1XK+NGERe8c0XB/Q4UnkPdhgj197QTLJsOQ0yxIyzBzDK+HorwMuv29IYe8xagzcqRwirBJNmV2NAkXQ3ATgyTt/nL/MoHJ6NJOPVmqBUskpoZWPYBlyP6xpt0EYr8dstmv39V5pQFb1lNPMhoVimrPY0pQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-test13-dev-taxi
      namespace: test13-cicd
    type: Opaque
status: {}
