apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-test13-dev-taxi
  namespace: test13-cicd
spec:
  encryptedData:
    webhook-secret-key: AgA6t6egICRD86hhGaA6eJDfbBYhD+QsUeyPB2lJiHpLQx/H1IfzM0oiB7HxJbcOD/m2VhtFsGBqmDAJP/Teux5fq2sTAsUdvkl30RVVlzZupCTK+2vUMMah4D/5zLCiOSQz+j9UejLZX+fcDRosGDvQY0r1Cz/251tvx96BVJdgtMQdesSFPDUMY95FBGaBMj43R0GNqN42Zm0fCINyBFKFZ5wTFWwMpdOwNsOWodpX9LZlC8V6YpJxFAkYeFZWmyGqp1GCEUtfQBEQQZ9Zabc3sIl4so12MEAvs6LpV/l1Yt0Ci2EXit4v9xFfsqc3krbPziT/LEezNHhm66vMBJUxYVyH87x89gamn0FJNV5iFh6HMFjteNdmdPQ/cQx3mcJTQfN4KGP1n9OerrUQa9UveC1loBE9xDJFCTHXFjpVufasjlpaPbR4V9EqQbAKvme6eNnPrkoMIAHtoFWY0pDRIMYcZZng0NnXdYA8biY/ScjCwsN74fNjGw29cFmTXuL5qkgtyZ31VO4OuB6WNhhRhk6ZUY2HU4IwT7oOYn+Mflh3xBda6AQ7rdi430b6IV7m9lKh+lHMGCXLGwPGYA0IGoMtds7nHBePkbE4BCBAYohBFu5pAN6h9GKs3gCFrczYIlgcchrVL+kPBlnTVzqm0JR0iahQOMNE0691puLAD4ZktpiyQr97u0FG1r1Wj3lHsKUHilKbrQH1tmIy7+aIS1ivxQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-test13-dev-taxi
      namespace: test13-cicd
    type: Opaque
status: {}
