apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-wed-dev-taxi
  namespace: wed-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAtqLUj3JcjeGAB8X0YFbq8/iK1A5d3GXDdZyGlwGZka4EX9nw1sOdPLR7LqMaWQjaL/ikIgkrLKrAqnq0IFmBvg+icn8dJ47Hglfi1t5Z3lYK5tj5YBJkE5TajAKdELYCqnkC8bwMgnS2Q2Ib1oHQtN2ferSZj5LWx/94OLqKjI5fGlvGzMPsEQ6avBVVIoFDPfqKV+0WDuWszhvpHjR7rrBjoE6/80tfBmqUsk6vdM9Nlv5sutnyL9KX2bhJ+5CoH71w/pX490rZ+MeAkRNyWqEpP/QWePr3mPdMF2O7bKD11hFh7ieSZ4dbgdcDNj3DGNU3fg+zd3vXV6fx8xpfguod/QxfyyoAycisQVELYd7NLO323/lJx06+AdhxW1kLSra/jey9hw55xQVhQ8m6Al2PJBv3t+JmJNXkAWd0aRn66gwsbUHxQCjPz1/uMkj/wA1EJVHgG+8wxfkWROJb/B1mtbLy50oVu5utMKKPRzTsp5wme1IAGuXs1q31XYtYDuVCBB80bF21YehUvJZbxyJhJNlOE97dgF9XdlU3b+RxuiubNC+zsbKICyHe/XRXHqmEHS0+zd8zADkOOX47GAFl3xySHMzXJV1Kbpj+bObk9xK9NwfX59t6zxeVfxgDPTUjOw4DDGhMPjKSHCx7uBBBQQdfAd1KSaiQX+JeG38DR9TQY7gSfm6Pv3ogDjrVyFV0=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-wed-dev-taxi
      namespace: wed-cicd
    type: Opaque
status: {}
