apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: taxi-svc
    app.kubernetes.io/part-of: taxi
  name: taxi-svc
  namespace: ishita-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: taxi-svc
    app.kubernetes.io/part-of: taxi
status:
  loadBalancer: {}
