apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-friday-prod-tax-svc
  namespace: friday-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAajmat84Mx68snwTW6jNxDVSg97Ez9NPLdUmOr6/vh/2yG42E3GWpiN0vFa0RQqmBaAXNAn4dTZNT9hieUpke/wNTXgWb6XNMXomMFu9K6DqAPko7iUPXyToz0RdZ+58DKn72e+LTv7QEqAuWGVEcdON3rKEwPmNmy7ZVBMefDlOGB2k22a9zFhj+HwOgMaMiYgXcy4LZN6O3hPc8+HzDMVRuWm+qv7uUEvtQu8JG4GCJXBp0rcZgt2XZ/LOwjJNR9jMnHOmcDlbE6ZFLleR59hxaCGf28/TvF5ZRyONB+619fJeyUqZ+k6QuoDSMRU4TpkaDAnDOnlEw4ZLzfdNKqxCPHDkUjl2CExR5koHMEoAWUpu5XV0CBKp4qzoBuO+V8D3e/lovaKNaZ78neiHe83wBaxRPFku5xQrVvO+gznAjzntZo2qWA6mvlD5M24d82eQ+6YT02TqGxESFKcT39Sq/9i40noXaa9VN6EPQz6ILnMwgkNbIXTtlhlsyhr+vNHH+akolY/S0Lm+n8htJNiXow3QEZFwRW7PAylTCvO44krthWfgJE9A3toOcP4O02YCbgs/BVAMg/ViY2lFOkHeV9RxvwvpfdhV+nhbsPPmT8L8RoYOMBjZM3LalnzR0aWRDr/ZRUgjNUU0CiRKIpCschoCrO/8Pgyc6lil0IJJTSEV9gr272JqNWvmbUiyP95b1OyhEMjfxhxjYQfrc7Hy9PBw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-friday-prod-tax-svc
      namespace: friday-cicd
    type: Opaque
status: {}
