apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: sunday-cicd
spec:
  encryptedData:
    token: AgBIxv1u4ecA0FIVO2fi9ZXuFzjDifCcty3V/2mudLmiRSsgYC5OSOEnK39SaSwL1V3d0Tu7qaYliBiNI7Jg7YKnCClnb38wubb4VSjsKPTERRuTvOnDEaD0ELVUw4KRHDA/h443K+vMzTF6I//XUhwSJ+vh7raskIki8Ox2R0Pv0R6qZHGM9SE5pMklqVIoJGyVhPzxzX0TDt7L4Ckv9rIOBZE3FtjTZNYKxxmlCtvY29B9GKpacxubeTX2BaNA+MM0+tNQ2AfuguSOEpFECF1y4pBDYF74x/qp2TWP/rjvx7lLBD+1wxCD45D2nNF5EaHGe5jFUNOa6MOI7ZxBXi2rzsa+ubgJ+mn2VNS1mVbAjuczVxDPkLibFQUwE+bs/H0mlPuiy/6GoJvBqTULzrYpss/2JNfJuqDjAfBgXVHji1DdA0x1dCdD+UxlZvAOhI9tJAVNirk8hk8xyExEQyG38ccCel4Bk1peBeqSd2zFqhcFAjG/mDKh3sq/5PQoSKxdD/lEqjBUzF2Bvdp671uCv7F9s9gH31xwMzqO+9UDVS5Hz6GxtZ9YSe0G6fSEJyGhuZDCpkE0cuA24G8om75qQSfwfOoy7dw9XroeToKLoz0d9qjLe09J7zzATqG1gsTXmyjADDnyriJfGtnfABf6mZKT4UfcRnnwEUFkcnCZUO80NzfJS6LhcOjnxrLbLJrMths3UdLdMdNQAoloCMm/uK9XMDGPvqlXXapA9uEGaM/tOCDP4bgT
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: sunday-cicd
    type: Opaque
status: {}
