apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: sunday-cicd
spec:
  encryptedData:
    token: AgCuXTMgpDJcuiqcivPeI9MHerxi87W3agXhkB9R3nFfSFVlR1cU3bP5sosUG37gw2JDBP3+wQKq7zUrBLDY40T0rePuft+TpPd/62DarUTPVbc/VNvWfi39zXu0tBixR0c6Sol0kxo8l+ujvtS/4Zctc6dpYqQadGUW/ni+PG8udKjuzFCiKFOPm5oxZ4j32+Bkz0zXtCA2mCiifRfCYKHiQJ2rpe+6Ro8yrrSz/F7HIuxoHJlNRYXbWozjK5JwpivugOQRUna+bud0bObI9eZiWzyJAVVDTz2Ib5Ff58SHH9MI+6wAMSetgD+Xs+rz/8c2pUNojuWHj0yZXuqAx2DuM9V6+UdpZFLhpNWaTSqMG6P+/NN3gU11Vr3OtpOovE8ciDf2CmaAyMnH/vY6RvFrq1NjoAajGOBr7Pfd837jV025AitBsx3pvqszFd7yyujq8iOykfV3Q+ghHM9AK6U2dzquaIXXAtY/G6gpd5+dHizXw8X0T7bLoD2YxE0PbXWR+rvUugxgmEHjYyBaxYtJduzKzEfc21YNu97BMW/1HeGKfSPNf20Lm0h/S0EDRY90QvWDRz3VImtoo2xqdAZ3s3W9Zz4+5r0Dqoysb8GwLY/fcuHb3FhdjYZv7BLmPWOdqOF4MvjBDuBTb6DfQjJP5PLWo9cYIalrk1l60yB5L8i1oNYBWBOJh/NinPzqhr8c10kUQuq6T+/SOkalznbud2KiCX3dL+uOs6YkFWfOSufvrkXQtsAj
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: sunday-cicd
    type: Opaque
status: {}
