apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: sunday-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAJ0JeCa/wFUP2XfgserE6hlPRZfGvvzxbGtvZpI1WPn/wmJvi2shTmoYHO1adh6HqAnNO6Oep05KYe7/BA8AyLihSse42S2fhbADgE5K64+YC+TQv8MLLi+Lau+gywv0KPFjNuwxPfTF4bomUWXYOcr8LLbTIph1erbjBBArCHLxfvAqfaD/Y9qjGyNaogtXlPPBZANiK+yDngaHLCQtpWDfUYsRjMsv2ZScivuS1b74UBE3co7sM6glGf3hs3TH7MWxlECWkJCFS7NM0egOxydgfkUJRVDJTOONg36cmBmPVPsl6swJain9rdC1ulFHMlZNp1jxybvfMTJ5usMIgQNjVuHkbYP6WbciEuU0aCzcdeZEsjDXtb1hKy5UgqA26G2yUrKizCajabAXNW6EIANYJ0AHKdjaY4pOZ5WYyHBq8UX1saZ8hcpUqQ/mtuB8qTmRFpuM2jWzFf0qWx7+zw5cb1Dnshba/vv2awYmArsUZBPdfjv3ERDPWdPkF8w/zo16n8ch87aMav6/XBbhlbqi0lpGiBrVVZve8H0KUwtE+ipu390v75Xxkt3wSI8xL8eg6mU/FxvtTavm90LxKj3tfEZE1l7y8yZrvaMYCdKRmeq1YPaEWnCnOhtqX36y8UQ/fgCibazNJ0i0QdYEYy7djnzDFIVVshRZra26bHGXhb1ELUntDAnA+oFEtzY70du3kovzhxUEbTGty6IN1j2Mcphg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: sunday-cicd
    type: Opaque
status: {}
