apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: sunday-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBW89JE0OsqMwYz2+pE32uoymE26UFWRdZJOU6VpgECritsPhNduO9n7Kox23FsBhx5pOh8dgORHPIRT6BYJFcznoaMztOf9g5gKa0+D5SBxxwgc3ILZU0bc7gg7Lu5TMk8LoY2FikWN0fVm3+A5Qb8HhHs1je5oMHhGKuWtYVzzQ3a7zrEOY1mGsPnu4IpBvxjp6XUl8wiV/3lOr5984VVrRfPgawJCcWUdQdfusz/QE9XKC40x4GIvr3V52Ra6WqpanLKNLOPXhNV4tY330yyhpYag3l+6dLlXDkPe/zjcMvIqq5eyGnF7/m6CodYH3Urmvnhdnjs/f5kqyD/eU+nN2L0cqwymwIlZUIVKl3XwpMiroBaL8pez9bdyowfVdhEghbK9cW/bzy9JOqcI1enp416uFtBK8MVr0ZEUUSAdWddUd0RbTRJ6wv2FVLYcVEAsn7T+DZyA43h3EtpF9MsOX+av2mOvaVjtRi8A7AwCfBl981c3gvDOhQG2NLY0+Tf8r/F1G+j66AvzRbESDOM5UGk6igQFdK2h1lV6E61fui6IUAqwqsYywVVD8Tli6pFDUlc0Dq81kED3UU9MkIl6Yniu2B1XKhFkm5XghiHBxyRAYpyxdL0bIuOMT7vDLU9sm5qM97fLnmOOU1I/xNfhAWmcyUYmpxddAuFYexnCQrG2fr5CZnKc5PqtkloRlG5pwoV7XGGZ3hP33tMFotHMZW38Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: sunday-cicd
    type: Opaque
status: {}
