apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-sunday-dev-taxi
  namespace: sunday-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBQz8j3sORt0Z6miwvBhNTWwJqYsiX2YGm/2A/dOn/hN6/9wsfSVjSJMpkTOuHuUbQEyEYvbe/kdCQ1WJIOW6ZJ/vtYogTZSd10kRJKPtpRHXuDCpXbiWrdyWWMxXZvCqx67PD14XnI+WRW35ivfV73dSQ1bbaCha6huW7q5Gds6EIEcCV+/sxACcfhByoOnFCTBEj4ly/FijpCyJBc0mQGNwo+MIYMCE9gOdyNldw5a3vGwHKi7Feh/9pivj9GHxuINVCwIUn3ViICGVNYNbHumTReahPNGbL4VCR7ea8jVO2blkEfffZKnK/Yo/XZAQF6Zbky+m4Uve1SSi12Zk2VVF4rOWK930mCyuYZyZ39gkgCS2HdgFwC/GB1UxAA+0Q2fhUCePyBZF3M9uqIPLTLHIkgORU8q58WN1O01ts5lMbeFPYQAajEzgo9LA0p9V1cTnpTqSpWQin7Y5TgnwCwvXCmeCq1lgyjFdMopUttbSlUyLKGu1RvgS5NZ0q5ExYGK6kZ47XDncI4UwXu76x/g5po6SR6dFggLQsK6QjXJbPCXmP+dvxZYDxlo6iByioui6D8PSt7n/MUwyIm0ewwTXzmYd3+p4veOlD4utswK27FIya/yg0daNrwr7zr8Sle8oigRkv3lg/ZeopDurc6pouHZ+DMvOYkb433/0080H49KDdBjqmOx0kqW8riCdvFjY8jJfiF+zmOFIQ6toZ4S55IKg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-sunday-dev-taxi
      namespace: sunday-cicd
    type: Opaque
status: {}
