apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-ishita-dev-taxi
  namespace: ishita-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAWqmEC0Ue6M3E9E1jEzlWOz+HoFcavQHtyCRYtb6qT4LNNkE1yu8fNykdPsgfJai0xleWdZ1Yu/J1RMupNT3zA2SeHprdH8r0QVqs9BgV48X/xMpDD+SKRtnZtsV6Ew4xWfUdd3ni3BJ2iWJIOCxuC24pBWU+n17jxIMUupcEtHjK5CmfbagNzNDbFpzdujhHUn6XCvAsfPMfabanKTI1u4IaqTMsPvIzrAX+NEUStsvHSx39c7KSmGQ/p3P8z5ctaN7D0xygxXEgZ8Fe4Q3gBH2ird7tTMKto9+ZKGm3wmGGj8/JU3ZaHrTmCsA3b0LcGRRGp9M2y88yIuDCW4QZ0bY1pBY97kUEcWAopWs5QkJ4l2qdKZxe/zshhr/+dxyExYajny3SLOJWiAXwcSpXXzxfMjRANrmrEWWMYy5xvFI3oUVvtJWTcsxgCDPaGlYkwj50WIGlncWkaVMa9T/A62HIevm2umB8/TA6dJhwLA71yUvmfu4yGR4TYWvKHngrciSwRDb9ED7gceL53QBbJEAQElrHUYRosHKzHEkF4MaoXYbAaKSSxxyWYLawbZvF2bbp2WibqC8t21gPSv44woQSCAQH5ZssZz8JoV7Brnk9h8WHBAMsj+5j7EyiDi1+E2oO9zCvcFqEK4KYVJXtU3q2VPYRrHkgGYNQ3LNUI9DiFVgYQ+OwO8DZ1IFoS4j58VpDhkooXJnCaHHxjzWLEoF8K7w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-ishita-dev-taxi
      namespace: ishita-cicd
    type: Opaque
status: {}
