apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-ishita-dev-taxi-svc
  namespace: ishita-cicd
spec:
  encryptedData:
    webhook-secret-key: AgC+vv6fK6vvLj88M3pzVcpdFk+aIJg/NroAQUAkuduUadNolQ5wlqXE2gURsbqsAwbiGv+GPbh22DpF7dCyGTlRgCEBjfYsvc9wIx3od5lKDPK8MK9lxo2R7hVMG78+kDOSLFNKgmj1eHYZ+ce4G3fKnCM5BBOHk7lQ2CVIFoMJn+YTujGPMUfHlTDpH60dqBSraqseuuK4nyTG0GbaTuKkTorWh6e617j/5qdn8TDAT7hOwBPUQU+tkMqgxn8q39vMVx4ODCgx7GU1vjTvOy8wD6Xkosxtb2PgXfThPqrHk4xFzpCFWI+iiDqknuDdgJGx46YJaS3kMxIuN6qL+vkc4U1HdioSFfqHz+b5cIVfrOU77bqvbGdwWhXbZdPtNVqaOZdAs07s97/MR6sIlZ4P6DTf+PUtZ4psrnTwMN4NII7827jh+urf0Kj5SMMWmig54oshlv4tneb2cTkf6CY380s8R7F3EXqMvz8cVe6Xdh79pvCxeSlOqQGRucEcg1uaZedNrhl01VB0OALnhRX/aRiBaE5rxtNgso6Q9N4RwfH9md1gdPpt1ER6g+FFn5emXtoEmb0FOY9WQyKaRigyV7ffUjvSg2FaP2irQPLbDRl6JeP82CPGVHgM+UnoLLbCRRbtDQv7z4eeyabayTqb77ha9FVggh10SqWQ5LH7HQq04HP/S3KHWnPsnWdszYRjoFVEaehugFanpKKYkIe+h9DBOg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-ishita-dev-taxi-svc
      namespace: ishita-cicd
    type: Opaque
status: {}
